"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import NavBar from "@/components/NavBar";

type Coin = { id:string; name:string; symbol:string; image:string; market_cap:number; total_volume:number; price_change_percentage_24h:number };
const chains = [{name:"Ethereum", key:"ethereum", tone:"#627eea", desc:"The settlement layer for DeFi, stablecoins, and thousands of on-chain applications."},{name:"Solana", key:"solana", tone:"#111", desc:"High-throughput execution for trading, consumer apps, and real-time markets."},{name:"Base", key:"base", tone:"#2455f5", desc:"An Ethereum L2 focused on accessible, low-cost on-chain products."},{name:"Sui", key:"sui", tone:"#55b9e8", desc:"Object-centric infrastructure built for fast, expressive digital ownership."},{name:"Robinhood", key:"robinhood", tone:"#ff6b00", desc:"A focused lens on the assets gaining attention across Robinhood markets."}];
const money=(n:number)=>n>=1e12?`$${(n/1e12).toFixed(2)}T`:n>=1e9?`$${(n/1e9).toFixed(2)}B`:n>=1e6?`$${(n/1e6).toFixed(1)}M`:`$${n.toFixed(0)}`;
export default function BlockchainsPage(){const [coins,setCoins]=useState<Coin[]>([]); useEffect(()=>{fetch("/api/coins/markets?per_page=100&page=1").then(r=>r.json()).then(setCoins).catch(()=>{});},[]); const stats=useMemo(()=>chains.map(chain=>{const list=coins.filter(c=>chain.key==="robinhood"?c.name.toLowerCase().includes("hood")||["dogecoin","shiba-inu","pepe"].includes(c.id):c.id.includes(chain.key)); return {...chain,count:list.length,volume:list.reduce((a,c)=>a+c.total_volume,0),change:list.length?list.reduce((a,c)=>a+c.price_change_percentage_24h,0)/list.length:0};}),[coins]); return <div className="min-h-screen bg-[#0b0d0f] text-[#f7f7f5]"><NavBar/><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><div className="border-b border-[#262a2d] pb-8"><p className="text-[10px] font-bold tracking-[0.22em] text-[#92999d]">ECOSYSTEM MAP</p><h1 className="mt-3 max-w-3xl text-4xl font-bold tracking-tight sm:text-6xl">Follow the rails<br/><span className="text-[#92999d]">behind the noise.</span></h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[#92999d]">Compare the ecosystems where emerging signals are forming. Each chain gets its own market lens inside the radar.</p></div><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{stats.map((chain)=><Link href={`/app?chain=${chain.name}`} key={chain.name} className="group rounded-2xl border border-[#262a2d] bg-[#16191b] p-5 transition hover:-translate-y-1 hover:border-[#f7f7f5]"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-2xl text-lg font-black text-white" style={{backgroundColor:chain.tone}}>{chain.name[0]}</span><span className="rounded-full border border-[#30363a] px-2.5 py-1 text-[10px] font-bold tracking-wide text-[#92999d]">{chain.count} TRACKED</span></div><h2 className="mt-8 text-xl font-bold">{chain.name}</h2><p className="mt-2 min-h-12 text-sm leading-5 text-[#92999d]">{chain.desc}</p><div className="mt-6 grid grid-cols-2 gap-2 border-t border-[#262a2d] pt-4"><div><span className="block text-[10px] font-bold tracking-widest text-[#687075]">24H FLOW</span><strong className="mt-1 block font-mono text-sm">{money(chain.volume)}</strong></div><div><span className="block text-[10px] font-bold tracking-widest text-[#687075]">AVG MOVE</span><strong className={`mt-1 block font-mono text-sm ${chain.change>=0?"text-emerald-400":"text-red-400"}`}>{chain.change>=0?"+":""}{chain.change.toFixed(2)}%</strong></div></div><span className="mt-5 block text-xs font-bold text-[#f7f7f5] opacity-60 transition group-hover:opacity-100">Explore {chain.name} radar →</span></Link>)}</div></main></div>}
